const solc = require('solc');
const fs = require('fs');
const path = require('path');

const contractPath = path.join(__dirname, 'src/contracts/SimpleTest.sol');
const source = fs.readFileSync(contractPath, 'utf8');

const input = {
  language: 'Solidity',
  sources: {
    'SimpleTest.sol': {
      content: source
    }
  },
  settings: {
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode']
      }
    }
  }
};

console.log('Compiling test contract...');
const output = JSON.parse(solc.compile(JSON.stringify(input)));

if (output.errors) {
  output.errors.forEach(error => {
    console.error(error.formattedMessage);
  });
  if (output.errors.some(error => error.severity === 'error')) {
    process.exit(1);
  }
}

const contract = output.contracts['SimpleTest.sol']['SimpleTest'];
const abi = contract.abi;
const bytecode = contract.evm.bytecode.object;

const outputContent = `// Auto-generated by compile-test.cjs
export const TEST_ABI = ${JSON.stringify(abi, null, 2)} as const;

export const TEST_BYTECODE = '0x${bytecode}';
`;

const outputPath = path.join(__dirname, 'src/contracts/test-abi.ts');
fs.writeFileSync(outputPath, outputContent);

console.log('Test contract compiled successfully!');
console.log('ABI and bytecode written to:', outputPath);
console.log('Bytecode length:', bytecode.length, 'characters');
