// Auto-generated by compile-test.cjs
export const TEST_ABI = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "value",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

export const TEST_BYTECODE = '0x6080604052348015600e575f5ffd5b50602a5f8190555060ac8060215f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80633fa4f24514602a575b5f5ffd5b60306044565b604051603b9190605f565b60405180910390f35b5f5481565b5f819050919050565b6059816049565b82525050565b5f60208201905060705f8301846052565b9291505056fea2646970667358221220511fece7b8036914fb5f7b1dcaee5a89ba6584d41451cb9ca65500e92ac325d164736f6c634300081e0033';
